# Generated by Django 5.0.6 on 2024-06-25 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("amount", models.IntegerField(verbose_name="Amount")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="Chocolate",
            field=models.IntegerField(default=0, verbose_name="Chocolate"),
        ),
        migrations.AddField(
            model_name="product",
            name="Coffee",
            field=models.IntegerField(default=0, verbose_name="Coffee"),
        ),
        migrations.AddField(
            model_name="product",
            name="Flour",
            field=models.IntegerField(default=0, verbose_name="Flour"),
        ),
        migrations.AddField(
            model_name="product",
            name="Sugar",
            field=models.IntegerField(default=0, verbose_name="Sugar"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
                verbose_name="Product Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
