# Generated by Django 5.0.6 on 2024-06-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storage_product_chocolate_product_coffee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Milk',
            field=models.IntegerField(default=0, verbose_name='Milk'),
        ),
    ]
